#!/bin/sh

# Cocotron Run
#
# Like xcrun - execute or locate Cocotron development tools and
# properties.
#
# NOTE: This is a basic script with no features. Essentially it just
# prepends a hard coded path to an invocation like gcc or nm.

COCOTRON_DIR="$HOME/Library/Developer/Cocotron"
COCOTRON_VERSION=1.0

COCOTRON_TOOLCHAIN_PLATFORM=Windows
COCOTRON_TOOLCHAIN_ARCH=i386
COCOTRON_TOOLCHAIN_COMPILER=gcc-4.3.1
COCOTRON_TOOLCHAIN_DIR=

COCOTRON_TOOLCHAIN_TRIPLE=
COCOTRON_CURRENT_BIN_DIR=

"$HOME/Library/Developer/Cocotron/1.0/Windows/i386/gcc-4.3.1/bin/i386-pc-mingw32msvc-$@"
